[package]
name = "rutify"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["json", "macros", "ws"] }
chrono = { version = "0.4", features = ["serde"] }
sea-orm = { version = "2.0.0-rc.30", features = ["macros", "runtime-tokio-native-tls", "sqlx-sqlite"] }
sea-orm-migration = {version = "2.0.0-rc.30"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.37", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait = "0.1.89"
dotenvy = "0.15"

